### ISSUE TITLE
Can't customize the output directory and bowerClean not working

### ISSUE THREAD

**Issue by aninda84** [craigburke/bower-installer-gradle#9]
Hello,

First of all thank you for your excellent work which is making our jobs easier. 

I am using your plugin and here is my simple build.gradle...

plugins {
    id 'com.craigburke.bower-installer' version '2.5.1'
}

apply plugin: 'java'

sourceSets {
    main {
        java {
            srcDir 'src/com/mypackage/controllers'
        }
        resources {
            srcDir 'WebContent/js'
        }
    }
}
bower {
    installBase = 'WebContent/js/libraries' // <1>

```
'angular'('1.3.x') {
    source 'angular.js' // <2>
}
```

}

2 issues ...
1. The angular is getting generated in a folder called 'library' under 'WebContent', not where I mentioned as 'installBase'.
2. The 'bowerClean' command is not deleting the contents pulled.

Please help.

**Comment by craigburke** [comment]
Thanks for the kind words!

That's very strange. Would you mind throwing up an example project so I can take a look?

**Comment by levsa** [comment]
We have seen a similar problem (on 2.4.1), but only on at least one windows pc, but not on any mac or unix. On a windows machine, the generated bower.json appears in gradle project directory (different from mac/unix), and it doesn't contain anything about installBase. Also, a bower_components/ is created directly in the project directory, instead of the given in installBase, which was build/assets/bower in our case. In this case, we are running gradle in a git bash, in case that can affect things.

**Comment by kelvix** [comment]
On Windows 10 with a similar issue. The following will not work

    installBase = "src/main/webapp/bower"

But this seemed to work for me.

    installBase = "src\\main\\webapp\\bower"

Seems like [this](https://github.com/craigburke/bower-installer-gradle/blob/b55d32357f39fdb8aa32f91a8b114ad436449c66/src/main/groovy/com/craigburke/gradle/BowerInstallerPlugin.groovy#L130-L138) method does some magic for us.

@craigburke would you be opposed to a PR or using something like the following?
    
    // new import
    import org.gradle.internal.os.OperatingSystem;

    private static void createSourceFolders(Project project, String installBase, sources) {
        if (OperatingSystem.current().isWindows()) {
            installBase = installBase.replace("/", File.separator)
        }

        sources.each { String moduleName, config ->
            config.mapping.each {
                String destination = it.find().value
                String path = destination.startsWith('../') ? destination.substring(3) : "${moduleName}/${destination}"
                project.file("${installBase}/${path}").parentFile.mkdirs()
            }
        }
    }

Seems like gradle makes inferring OS rather easy with [isWindows()](https://docs.gradle.org/current/javadoc/org/gradle/nativeplatform/platform/OperatingSystem.html#isWindows()) and other related methods.

I can't think of any immediate downsides to this on Windows since `/` is an invalid character to use as a file name as noted [here](https://support.microsoft.com/en-us/kb/177506).

I suggest the implementation of such checks because my team of mostly OS X users is unlikely going to want to commit `/` to `\\` changes to our repo. In the short term I'll use a modified jar to build stuff.

**Comment by craigburke** [comment]
Closing this since this plugin is replaced by the client dependencies gradle plugin:
https://github.com/craigburke/client-dependencies-gradle
